import zipfile, os

zip_path = r'C:\Users\a844699\AppData\Local\Temp\vienna-convention.zip'
out_dir = r'C:\Development\permis2.0\apps\web\public\images\signs'
prefix = 'vienna-convention-main/Traffic_Signs/'
os.makedirs(out_dir, exist_ok=True)

codes = {
  'A1a':'A:Danger/VIENNA:A1a/VIENNA:A1a-Aa-V1.svg',
  'A1b':'A:Danger/VIENNA:A1b/VIENNA:A1b-Aa-V1.svg',
  'A1c':'A:Danger/VIENNA:A1c/VIENNA:A1c-Aa-V1.svg',
  'A1d':'A:Danger/VIENNA:A1d/VIENNA:A1d-Aa-V1.svg',
  'A2a':'A:Danger/VIENNA:A2a/VIENNA:A2a-Aa-V1.svg',
  'A3a':'A:Danger/VIENNA:A3a/VIENNA:A3a-Aa-V1.svg',
  'A3b':'A:Danger/VIENNA:A3b/VIENNA:A3b-Aa-V1.svg',
  'A4a':'A:Danger/VIENNA:A4a/VIENNA:A4a-Aa-V1.svg',
  'A4b':'A:Danger/VIENNA:A4b/VIENNA:A4b-Aa-V1.svg',
  'A5':'A:Danger/VIENNA:A5/VIENNA:A5-Aa-V1.svg',
  'A6':'A:Danger/VIENNA:A6/VIENNA:A6-Aa-V1.svg',
  'A7a':'A:Danger/VIENNA:A7a/VIENNA:A7a-Aa-V1.svg',
  'A7b':'A:Danger/VIENNA:A7b/VIENNA:A7b-Aa-V1.svg',
  'A7c':'A:Danger/VIENNA:A7c/VIENNA:A7c-Aa-V1.svg',
  'A8':'A:Danger/VIENNA:A8/VIENNA:A8-Aa-V1.svg',
  'A9':'A:Danger/VIENNA:A9/VIENNA:A9-Aa-V1.svg',
  'A13':'A:Danger/VIENNA:A13/VIENNA:A13-Aa-V1.svg',
  'A14':'A:Danger/VIENNA:A14/VIENNA:A14-Aa-V1.svg',
  'A15a':'A:Danger/VIENNA:A15a/VIENNA:A15a-Aa-V1.svg',
  'A16':'A:Danger/VIENNA:A16/VIENNA:A16-Aa-V1.svg',
  'A17':'A:Danger/VIENNA:A17/VIENNA:A17-Aa-V1.svg',
  'A17a':'A:Danger/VIENNA:A17a/VIENNA:A17a-Aa-V1.svg',
  'A17b':'A:Danger/VIENNA:A17b/VIENNA:A17b-Aa-V1.svg',
  'A18a':'A:Danger/VIENNA:A18a/VIENNA:A18a-Aa-V1.svg',
  'A18e':'A:Danger/VIENNA:A18e/VIENNA:A18e-Aa-V1.svg',
  'A18f':'A:Danger/VIENNA:A18f/VIENNA:A18f-Aa-V1.svg',
  'A19a':'A:Danger/VIENNA:A19a/VIENNA:A19a-Aa-V1.svg',
  'A20':'A:Danger/VIENNA:A20/VIENNA:A20-Aa-V1.svg',
  'A22':'A:Danger/VIENNA:A22/VIENNA:A22-Aa-V1.svg',
  'A23':'A:Danger/VIENNA:A23/VIENNA:A23-Aa-V1.svg',
  'A25':'A:Danger/VIENNA:A25/VIENNA:A25-Aa-V1.svg',
  'A26a':'A:Danger/VIENNA:A26a/VIENNA:A26a-Aa-V1.svg',
  'A26b':'A:Danger/VIENNA:A26b/VIENNA:A26b-Aa-V1.svg',
  'A27':'A:Danger/VIENNA:A27/VIENNA:A27-Aa-V1.svg',
  'A2c':'A:Danger/VIENNA:A2c/VIENNA:A2c-Aa-V1.svg',
  'A32':'A:Danger/VIENNA:A32/VIENNA:A32-Aa-V1.svg',
  'A3c':'A:Danger/VIENNA:A3c/VIENNA:A3c-Aa-V1.svg',
  'AB1':'B:Priority/VIENNA:AB1/VIENNA:AB1-V1.svg',
  'AB2':'B:Priority/VIENNA:AB2/VIENNA:AB2-V1.svg',
  'AB25':'B:Priority/VIENNA:AB25/VIENNA:AB25-V1.svg',
  'AB3a':'B:Priority/VIENNA:AB3a/VIENNA:AB3a-V1.svg',
  'AB6':'B:Priority/VIENNA:AB6/VIENNA:AB6-V1.svg',
  'AB7':'B:Priority/VIENNA:AB7/VIENNA:AB7-V1.svg',
  'AK1':'E:Special/VIENNA:AK1/VIENNA:AK1-V1.svg',
  'AK4':'E:Special/VIENNA:AK4/VIENNA:AK4-V1.svg',
  'B0':'C:Prohibitory/VIENNA:B0/VIENNA:B0-V1.svg',
  'B1':'C:Prohibitory/VIENNA:B1/VIENNA:B1-V1.svg',
  'B2a':'C:Prohibitory/VIENNA:B2a/VIENNA:B2a-V1.svg',
  'B2b':'C:Prohibitory/VIENNA:B2b/VIENNA:B2b-V1.svg',
  'B2c':'C:Prohibitory/VIENNA:B2c/VIENNA:B2c-V1.svg',
  'B3':'C:Prohibitory/VIENNA:B3/VIENNA:B3-V1.svg',
  'B3a':'C:Prohibitory/VIENNA:B3a/VIENNA:B3a-V1.svg',
  'B3b':'C:Prohibitory/VIENNA:B3b/VIENNA:B3b-V1.svg',
  'B4':'C:Prohibitory/VIENNA:B4/VIENNA:B4-V1.svg',
  'B5':'C:Prohibitory/VIENNA:B5/VIENNA:B5-V1.svg',
  'B6':'C:Prohibitory/VIENNA:B6/VIENNA:B6-V1.svg',
  'B6a':'C:Prohibitory/VIENNA:B6a/VIENNA:B6a-V1.svg',
  'B7':'C:Prohibitory/VIENNA:B7/VIENNA:B7-V1.svg',
  'B9':'C:Prohibitory/VIENNA:B9/VIENNA:B9-V1.svg',
  'B9a':'C:Prohibitory/VIENNA:B9a/VIENNA:B9a-V1.svg',
  'C1':'D:Mandatory/VIENNA:C1/VIENNA:C1-V1.svg',
  'C1a':'D:Mandatory/VIENNA:C1a/VIENNA:C1a-V1.svg',
  'C1b':'D:Mandatory/VIENNA:C1b/VIENNA:C1b-V1.svg',
  'C1c':'D:Mandatory/VIENNA:C1c/VIENNA:C1c-V1.svg',
  'C2':'D:Mandatory/VIENNA:C2/VIENNA:C2-V1.svg',
  'C3a':'D:Mandatory/VIENNA:C3a/VIENNA:C3a-V1.svg',
  'C3b':'D:Mandatory/VIENNA:C3b/VIENNA:C3b-V1.svg',
  'C3c':'D:Mandatory/VIENNA:C3c/VIENNA:C3c-V1.svg',
  'C3d':'D:Mandatory/VIENNA:C3d/VIENNA:C3d-V1.svg',
  'C3e':'D:Mandatory/VIENNA:C3e/VIENNA:C3e-V1.svg',
  'C3h':'D:Mandatory/VIENNA:C3h/VIENNA:C3h-V1.svg',
  'C3i':'D:Mandatory/VIENNA:C3i/VIENNA:C3i-V1.svg',
  'C3j':'D:Mandatory/VIENNA:C3j/VIENNA:C3j-V1.svg',
  'C3k':'D:Mandatory/VIENNA:C3k/VIENNA:C3k-V1.svg',
  'C3l':'D:Mandatory/VIENNA:C3l/VIENNA:C3l-V1.svg',
  'C4a':'D:Mandatory/VIENNA:C4a/VIENNA:C4a-V1.svg',
  'C4b':'D:Mandatory/VIENNA:C4b/VIENNA:C4b-V1.svg',
  'C5':'D:Mandatory/VIENNA:C5/VIENNA:C5-V1.svg',
  'C6':'D:Mandatory/VIENNA:C6/VIENNA:C6-V1.svg',
  'C7':'D:Mandatory/VIENNA:C7/VIENNA:C7-V1.svg',
  'C8':'D:Mandatory/VIENNA:C8/VIENNA:C8-V1.svg',
  'C9':'D:Mandatory/VIENNA:C9/VIENNA:C9-V1.svg',
  'C10':'D:Mandatory/VIENNA:C10/VIENNA:C10-V1.svg',
  'C11a':'D:Mandatory/VIENNA:C11a/VIENNA:C11a-V1.svg',
  'C11b':'D:Mandatory/VIENNA:C11b/VIENNA:C11b-V1.svg',
  'C12':'D:Mandatory/VIENNA:C12/VIENNA:C12-V1.svg',
  'C13a':'D:Mandatory/VIENNA:C13a/VIENNA:C13a-V1.svg',
  'C13b':'D:Mandatory/VIENNA:C13b/VIENNA:C13b-V1.svg',
  'C14':'D:Mandatory/VIENNA:C14/VIENNA:C14-V1.svg',
  'C15':'D:Mandatory/VIENNA:C15/VIENNA:C15-V1.svg',
  'C16':'D:Mandatory/VIENNA:C16/VIENNA:C16-V1.svg',
  'C17a':'D:Mandatory/VIENNA:C17a/VIENNA:C17a-V1.svg',
  'C17b':'D:Mandatory/VIENNA:C17b/VIENNA:C17b-V1.svg',
  'C17c':'D:Mandatory/VIENNA:C17c/VIENNA:C17c-V1.svg',
  'C18':'D:Mandatory/VIENNA:C18/VIENNA:C18-V1.svg',
  'C19':'D:Mandatory/VIENNA:C19/VIENNA:C19-V1.svg',
  'C20a':'D:Mandatory/VIENNA:C20a/VIENNA:C20a-V1.svg',
  'C20b':'D:Mandatory/VIENNA:C20b/VIENNA:C20b-V1.svg',
  'D1':'G:Direction/VIENNA:D1/VIENNA:D1-V1.svg',
  'D2':'G:Direction/VIENNA:D2/VIENNA:D2-V1.svg',
  'D3':'G:Direction/VIENNA:D3/VIENNA:D3-V1.svg',
  'D4':'G:Direction/VIENNA:D4/VIENNA:D4-V1.svg',
  'D5':'G:Direction/VIENNA:D5/VIENNA:D5-V1.svg',
  'D6':'G:Direction/VIENNA:D6/VIENNA:D6-V1.svg',
  'D7':'G:Direction/VIENNA:D7/VIENNA:D7-V1.svg',
  'D8':'G:Direction/VIENNA:D8/VIENNA:D8-V1.svg',
  'D9':'G:Direction/VIENNA:D9/VIENNA:D9-V1.svg',
  'D10a':'G:Direction/VIENNA:D10a/VIENNA:D10a-V1.svg',
  'D10b':'G:Direction/VIENNA:D10b/VIENNA:D10b-V1.svg',
  'D10c':'G:Direction/VIENNA:D10c/VIENNA:D10c-V1.svg',
  'D11':'G:Direction/VIENNA:D11/VIENNA:D11-V1.svg',
  'G13':'G:Direction/VIENNA:G13/VIENNA:G13-V1.svg',
  'G14':'G:Direction/VIENNA:G14/VIENNA:G14-V1.svg',
  'G17':'G:Direction/VIENNA:G17/VIENNA:G17-V1.svg',
  'G18':'G:Direction/VIENNA:G18/VIENNA:G18-V1.svg',
  'G19':'G:Direction/VIENNA:G19/VIENNA:G19-V1.svg',
  'G20':'G:Direction/VIENNA:G20/VIENNA:G20-V1.svg',
  'G21':'G:Direction/VIENNA:G21/VIENNA:G21-V1.svg',
  'G22a':'G:Direction/VIENNA:G22a/VIENNA:G22a-V1.svg',
  'G22b':'G:Direction/VIENNA:G22b/VIENNA:G22b-V1.svg',
  'G22c':'G:Direction/VIENNA:G22c/VIENNA:G22c-V1.svg',
  'G23a':'G:Direction/VIENNA:G23a/VIENNA:G23a-V1.svg',
  'G23b':'G:Direction/VIENNA:G23b/VIENNA:G23b-V1.svg',
  'G24a':'G:Direction/VIENNA:G24a/VIENNA:G24a-V1.svg',
  'G24b':'G:Direction/VIENNA:G24b/VIENNA:G24b-V1.svg',
  'G24c':'G:Direction/VIENNA:G24c/VIENNA:G24c-V1.svg',
  'E3a':'E:Special/VIENNA:E3a/VIENNA:E3a-V1.svg',
  'E3b':'E:Special/VIENNA:E3b/VIENNA:E3b-V1.svg',
  'E5a':'E:Special/VIENNA:E5a/VIENNA:E5a-V1.svg',
  'E5b':'E:Special/VIENNA:E5b/VIENNA:E5b-V1.svg',
  'E6a':'E:Special/VIENNA:E6a/VIENNA:E6a-V1.svg',
  'E6b':'E:Special/VIENNA:E6b/VIENNA:E6b-V1.svg',
  'E7a':'E:Special/VIENNA:E7a/VIENNA:E7a-V1.svg',
  'E7b':'E:Special/VIENNA:E7b/VIENNA:E7b-V1.svg',
  'E7c':'E:Special/VIENNA:E7c/VIENNA:E7c-V1.svg',
  'E7d':'E:Special/VIENNA:E7d/VIENNA:E7d-V1.svg',
  'E8a':'E:Special/VIENNA:E8a/VIENNA:E8a-V1.svg',
  'E8b':'E:Special/VIENNA:E8b/VIENNA:E8b-V1.svg',
  'E8c':'E:Special/VIENNA:E8c/VIENNA:E8c-V1.svg',
  'E8d':'E:Special/VIENNA:E8d/VIENNA:E8d-V1.svg',
  'E9a':'E:Special/VIENNA:E9a/VIENNA:E9a-V1.svg',
  'E10a':'E:Special/VIENNA:E10a/VIENNA:E10a-V1.svg',
  'E11a':'E:Special/VIENNA:E11a/VIENNA:E11a-V1.svg',
  'E11b':'E:Special/VIENNA:E11b/VIENNA:E11b-V1.svg',
  'E12a':'E:Special/VIENNA:E12a/VIENNA:E12a-V1.svg',
  'E12b':'E:Special/VIENNA:E12b/VIENNA:E12b-V1.svg',
  'E13a':'E:Special/VIENNA:E13a/VIENNA:E13a-V1.svg',
  'E13b':'E:Special/VIENNA:E13b/VIENNA:E13b-V1.svg',
  'E14a':'E:Special/VIENNA:E14a/VIENNA:E14a-V1.svg',
  'E14b':'E:Special/VIENNA:E14b/VIENNA:E14b-V1.svg',
  'E14c':'E:Special/VIENNA:E14c/VIENNA:E14c-V1.svg',
  'E15':'E:Special/VIENNA:E15/VIENNA:E15-V1.svg',
  'E16':'E:Special/VIENNA:E16/VIENNA:E16-V1.svg',
  'F1a':'F:Information/VIENNA:F1a/VIENNA:F1a-V1.svg',
  'F1b':'F:Information/VIENNA:F1b/VIENNA:F1b-V1.svg',
  'F1c':'F:Information/VIENNA:F1c/VIENNA:F1c-V1.svg',
  'F2':'F:Information/VIENNA:F2/VIENNA:F2-V1.svg',
  'F3':'F:Information/VIENNA:F3/VIENNA:F3-V1.svg',
  'F4':'F:Information/VIENNA:F4/VIENNA:F4-V1.svg',
  'F5':'F:Information/VIENNA:F5/VIENNA:F5-V1.svg',
  'F6':'F:Information/VIENNA:F6/VIENNA:F6-V1.svg',
  'F7':'F:Information/VIENNA:F7/VIENNA:F7-V1.svg',
  'F8':'F:Information/VIENNA:F8/VIENNA:F8-V1.svg',
  'F9':'F:Information/VIENNA:F9/VIENNA:F9-V1.svg',
  'F10':'F:Information/VIENNA:F10/VIENNA:F10-V1.svg',
  'F11':'F:Information/VIENNA:F11/VIENNA:F11-V1.svg',
  'F12':'F:Information/VIENNA:F12/VIENNA:F12-V1.svg',
  'F13':'F:Information/VIENNA:F13/VIENNA:F13-V1.svg',
  'F14':'F:Information/VIENNA:F14/VIENNA:F14-V1.svg',
  'F15':'F:Information/VIENNA:F15/VIENNA:F15-V1.svg',
  'F16':'F:Information/VIENNA:F16/VIENNA:F16-V1.svg',
  'F17':'F:Information/VIENNA:F17/VIENNA:F17-V1.svg',
  'F18':'F:Information/VIENNA:F18/VIENNA:F18-V1.svg',
  'H1':'H:Additional/VIENNA:H1/VIENNA:H1-V1.svg',
  'M1':'C:Prohibitory/VIENNA:M1/VIENNA:M1-V1.svg',
  'M2':'C:Prohibitory/VIENNA:M2/VIENNA:M2-V1.svg',
  'M3':'C:Prohibitory/VIENNA:M3/VIENNA:M3-V1.svg',
}

with zipfile.ZipFile(zip_path, 'r') as z:
    names = z.namelist()
    copied = 0
    for code, rel in codes.items():
        full = 'vienna-convention-main/Traffic_Signs/' + rel
        if full not in names:
            print('NOT_FOUND\t' + code)
            continue
        data = z.read(full)
        dest = os.path.join(out_dir, code + '.svg')
        with open(dest, 'wb') as f:
            f.write(data)
        copied += 1
print('RESTORED\t' + str(copied) + '/' + str(len(codes)))
